In [20]:
import numpy as np
import pandas as pd
df=np.random.rand(4,3)
print(df)
new=np.array(df.columns[:-1])
print(new.shape)
print(new)

[[0.69003785 0.45596742 0.17387848]
 [0.07803368 0.51576749 0.27601491]
 [0.8689517  0.64202222 0.26044265]
 [0.12458188 0.73722607 0.22256239]]


AttributeError: 'numpy.ndarray' object has no attribute 'columns'