In [6]:
import numpy as np
import pandas as pd
X=[[0,1,1],[0,1,0],[0,0,1],[0,0,0],[1,1,1],[1,1,0],[1,0,1],[1,0,0]]
W=np.ones(3,)
ans=np.ones(8,)
for i in range (len(X)):
    ans[i]=np.dot(X[i],W)
print(ans)

[2. 1. 1. 0. 3. 2. 2. 1.]


In [7]:
import numpy as np
import pandas as pd
X=[[1,1,1],[1,1,0],[1,0,1],[1,0,0],[0,1,1],[0,1,0],[0,0,1],[0,0,0]]
W=np.ones(3,)
ans=np.ones(8,)
for i in range (len(X)):
    ans[i]=np.dot(X[i],W)
print(ans)

[3. 2. 2. 1. 2. 1. 1. 0.]


In [8]:
import numpy as np
import pandas as pd
X=[[0,1],[0,0],[0,0],[1,1]]
W=np.ones(2,)
ans=np.ones(4,)
for i in range (len(X)):
    ans[i]=np.dot(X[i],W)
print(ans)

[1. 0. 0. 2.]


In [9]:
import numpy as np
import pandas as pd
X=[[0,0],[1,1],[1,1],[1,1]]
W=np.ones(2,)
ans=np.ones(4,)
for i in range (len(X)):
    ans[i]=np.dot(X[i],W)
print(ans)

[0. 2. 2. 2.]


In [15]:
import numpy as np
import pandas as pd
X=[[1,-1,2],[1,1,3],[-1,1,0],[1,2,4],[3,-1,-1]]
W=[[-1],[1],[-1]]
Y=[[1],[4],[-1],[-2],[0]]
ans=[[1],[1],[1],[1],[1]]
for i in range (len(X)):
    ans[i]=np.dot(X[i],W)
print(ans)

[array([-4]), array([-3]), array([2]), array([-3]), array([-3])]


In [16]:
def mean_square_error(X:np.ndarray, Y:np.ndarray, current_W:np.ndarray):
    square_error = 0 
    Y_pred = np.empty_like(Y)
	

    for i in range(len(X)):
        Y_pred[i]=np.dot(current_W, X[i])
        temp = (np.power((Y[i] -Y_pred[i]),2))
        square_error += temp 
    return 0.5*square_error

def gradient_descent(X:np.ndarray, Y:np.ndarray,r:float,threshold):
	costs = []  
	current_W = np.zeros(X.shape[1])
	#print(W.shape)
	#print(r)

	norm = math.inf

	while norm > threshold:
		updated_W = np.zeros(X.shape[1])
		
		for j in range(len(X[0])):
			temp = 0 
			for i in range(len(X)):
				temp += X[i][j] *(Y[i] - np.dot(current_W, X[i]))
			updated_W[j] = temp 

		updated_W = current_W + r*updated_W
		#r=r*0.5
		norm = LA.norm(current_W - updated_W)
		costs.append(mean_square_error(X, Y, current_W))
		#r=r*0.5
		current_W = updated_W

	#costs.append(mean_square_error(X, Y, W))
	return current_W, costs

def stochastic_gradient_descent(X, Y, r,threshold):

	current_W = np.zeros(X.shape[1])
	norm = math.inf
	costs = [mean_square_error(X, Y, current_W)]
	while norm > threshold:
		i = random.randrange(len(X))
		running_w = np.zeros(X.shape[1])
		for j in range(len(X[0])): 
			running_w[j] = X[i][j] *(Y[i] - np.dot(current_W, X[i]))
		updated_W = current_W + r*running_w
		current_W = updated_W
		new_cost = mean_square_error(X, Y, current_W) 
		norm = abs(new_cost - costs[-1])
		costs.append(new_cost)

	return current_W, costs